### ISSUE TITLE
Filename collision edge case.

### ISSUE THREAD

**Issue by embolden** [mus-candidus/ImagEd#1]
Hey friend, love this mod.  Ran into an edge case today and wanted to ask about maybe changing the suffix to the hash code.

Here's a mod that I'm working on that uses it: https://github.com/embolden/Recolor-Tools/blob/master/%5BCP%2CIE%5D%20Recolor%20Scythe/content.json#L139 and I'm linking right to the spot where I'm having an issue.

Currently ImagEd is using saturation mode and blend color to generate the suffix.  I have two `EditImage` actions with different masks but possibly the same saturation modes and blend value.  If they both have the same, only the latter one is applied.  I'm trying to avoid having to create a 3rd mask with both and juggling the logic in Content Patcher.

I noticed there is `GetHashCode` in `RecolorTokenArguments.cs` and I was able to compile a version of this mod where I changed the suffix to:

```
string hash = inputData.GetHashCode().ToString();
string suffix = $"recolored_{hash}";
monitor_.Log($"{suffix}");
```

![image](https://user-images.githubusercontent.com/1679978/102932443-e8059e00-4465-11eb-99f0-879905cc4efd.png)

I didn't have any performance issues and am going to be doing more testing but I think this solves the potential for collisions with my edge case.  Thanks.

**Comment by mus-candidus** [comment]
Thanks for pointing this out. I wanted unique filenames but didn't think about using GetHashCode() although it's the better choice here. Your change will be in next release (probably version 1.1).
